### ISSUE TITLE
Query fails with syntax error for specific string value "a"

### ISSUE THREAD

**Issue by krisztian-gajdar** [redis/docs#886] opened 2024-11-18 11:04 UTC
### Description
When querying RediSearch with exact text match, the query fails with a syntax error specifically when searching for the value "a", while it works fine for other single-character values like "b".

### Reproduction Steps
1. Create an index with text field containing single-character values
2. Run the following queries:
FT.SEARCH idx_2dd612eb422d2f6c '@schema_fieldParagraphSchema_body_2:"b"'
FT.SEARCH idx_2dd612eb422d2f6c '@schema_fieldParagraphSchema_body_2:"a"'

### Expected Behavior
Both queries should work identically since they follow the same syntax, just with different search values.

### Actual Behavior
- Query with value "b" returns results as expected
- Query with value "a" throws a syntax error `Syntax error at offset 42 near a`

### Environment
- Platform: Cloud

### Additional Context
This appears to be a parser-specific issue where the character "a" is being treated differently from other single-character values. This could be related to "a" being a common word or having special meaning in the query parser.

### Impact
This issue prevents querying for specific text values containing "a", which is a significant limitation for text search functionality.

### Note
FT.SEARCH idx_2dd612eb422d2f6c '@schema_fieldParagraphSchema_body_2:a'
this returns no result, but the value is there

We also ran into an issue where 2 fields contained "true"/"false" string values, and we were able to filter one column correctly, but in the other column we could only filter for "true", and "false" produced the same issue as described above.

**Comment by benoitdion** [comment] 2024-11-18 14:56
@krisztian-gajdar what version of redisearch are you using?

**Comment by krisztian-gajdar** [comment] 2024-11-18 15:01
@benoitdion There was a mistake in the issue title, I am using the free tier of redis cloud, and running the queries using the redis insight desktop app.

**Comment by dwdougherty** [comment] 2024-11-20 17:42
@krisztian-gajdar Based on some internal chatter, it seems that some other Redis folks have been in touch with you to help. Is your question resolved?

**Comment by adrianoamaral** [comment] 2024-11-20 18:20
@krisztian-gajdar This is the expected behaviour since the term that you're looking for is one [stop word](https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/stopwords/#:~:text=Redis%20Stack%20has%20a%20default,are%20discarded%20and%20not%20indexed.) "a". If you try with "an" or "the" will also get no response. If you want to query for "a" you need to remove it from the STOPWORD when creating the index

**Comment by dwdougherty** [comment] 2024-11-20 18:26
Thank you, @adrianoamaral ! I'll go ahead and close this issue.

**Closed by dwdougherty** 2024-11-20 18:26 UTC
Labels: question
