### ISSUE TITLE
Feedback: Redis products

### ISSUE THREAD

**Issue by Herbinz** [redis/docs#547] opened 2024-08-13 23:58 UTC
I am new to Redis.  I have signed up with Azure.  

I am trying to use Redis Insight to connect to the database.

hfl.redis.cache.windows.net port 6380

Redis Insight cannot connect to the database.

I know Redis Insight works because I can use it on a local machine.

I can telnet to the database, so I know the port is open.

Please advise,

![screen_19](https://github.com/user-attachments/assets/3e8535c9-6b92-48d8-8dc6-2955624739dd)

**Comment by mich-elle-luna** [comment] 2024-08-14 00:39
Thanks for this question, let me cc @ViktarStarastsenka in case he can help you out.

**Comment by mich-elle-luna** [comment] 2024-08-14 00:46
Hi, actually Viktar is off today. Here is a set of steps from our chatbot at redis.io/chat for troubleshooting in the meantime: 

It seems like you've correctly set up your Redis instance in Azure and verified that the port is open by using telnet. However, you're facing issues connecting with Redis Insight. Here's a checklist to troubleshoot and resolve the issue:

    Connection URL and Credentials:

    Ensure you are using the correct hostname (hfl.redis.cache.windows.net) and port (6380).
    Make sure you are using the correct access keys (primary or secondary) for authentication.

    SSL/TLS Settings:

    Azure Cache for Redis requires SSL/TLS connections by default. Make sure you have enabled SSL/TLS in your Redis Insight connection settings.
    In Redis Insight, tick the checkbox for "Use TLS" to ensure a secure connection.

    Firewall and Network Security:

    Verify that there are no firewall rules blocking the connection from your local machine to the Azure Redis instance.
    Ensure that network security groups in Azure allow inbound traffic on port 6380.

    Redis Insight Configuration:

    Make sure Redis Insight is updated to the latest version.
    Recheck the configuration settings for Redis Insight to ensure there are no typos or incorrect details.

    Testing with Redis CLI:

    You can use the redis-cli to test the connection from your local machine. Run the following command to verify: redis
     redis-cli -h hfl.redis.cache.windows.net -p 6380 -a <your_access_key> --tls
    Replace <your_access_key> with your actual access key.

    Logs and Error Messages:

    Check Redis Insight logs for any specific error messages that may indicate the root cause.
    If Redis Insight provides detailed error messages, share them to better diagnose the problem.

For detailed guidance, you can refer to this [tutorial](https://redis.io/learn/create/azurefunctions).

If you follow these steps and still encounter issues, please let me know the specific error message, and I can assist you further.

**Comment by mich-elle-luna** [comment] 2024-08-21 21:21
Closing as there was no reply, but please re-open if you need more help.

**Closed by mich-elle-luna** 2024-08-21 21:21 UTC
